export const items = [
  {
    id: Math.random(),
    title: "وجبه فطار",
    description: "فطار المعلم الوحش التنين ",
    price: "50 جنيه",
    Category: "فطار",
    imgurl: "1.jpg",
  },
  {
    id: Math.random(),
    title: "وجبه غدا",
    description: "الغداء المجنح",
    price: "200 جنيه",
    Category: "غداء",
    imgurl: "2.jpg",
  },
  {
    id: Math.random(),
    title: "وجبه عشاء",
    description: "ارفع شعار لا لربط الحزام",
    price: "70 جنيه",
    Category: "عشاء",
    imgurl: "3.jpg",
  },
  {
    id: Math.random(),
    title: "وجبه غداء ممتاز",
    description: "وجبه ابو الخير يعني كلها خير",
    price: "300 جنيه",
    Category: "غداء",
    imgurl: "4.jpg",
  },
  {
    id: Math.random(),
    title: "وجبه عشاء درجه اولى",
    description: "اتلحلح وخليك هاي كلاس",
    price: "175 جنيه",
    Category: "عشاء",
    imgurl: "5.jpg",
  },
  {
    id: Math.random(),
    title: "وجبه فطار ابو الخير باشا",
    description: "ابو الخير باشا المجنح التنين",
    price: "125 جنيه",
    Category: "فطار",
    imgurl: "6.jpg",
  },
  {
    id: Math.random(),
    title: " سناك مطاعم ابو الخير ",
    description: "خدلك سناك وخليك مجنح",
    price: "75 جنيه",
    Category: "سناك",
    imgurl: "7.jpg",
  },
];
